# ============================ MyBatis Plus =========================================
mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  # 修改 mybatis 的 DefaultEnumTypeHandler
  #configuration:
    # default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler