# ============================ 自定义 swagger信息 =================
# 自定义 knife4j 信息
swagger:
  base-package: top.it6666.controller
  description: Service-MyBatis-Plus API document
  title: Service-MyBatis-Plus-API
  version: 1.0

swagger2:
  title: Service-MyBatis-Plus App
  description: Service-MyBatis-Plus App API document

# ============================ Spring =========================================
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    #jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      schema-locations:
        - classpath:db/h2/schema-customer-h2.sql
        - classpath:db/h2/schema-user-h2.sql
      data-locations:
        - classpath:db/h2/data-customer-h2.sql
        - classpath:db/h2/data-user-h2.sql
#  datasource:
    # MySql DataSource Config
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mybatisplus?useUnicode=true&useSSL=false&characterEncoding=utf8
#    username: root
#    password: root
  # mvc
  mvc:
    pathmatch:
      # 路径匹配策略  spring-boot 2.6 之后更改了匹配策略
      # Springboot2.6以后将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser，导致出错
      matching-strategy: ant_path_matcher
  # ============================ Spring Boot Admin ============================
  # 注册到 Spring Boot Admin
  boot:
    admin:
      client:
        url: http://127.0.0.1:50004
        instance:
          service-base-url: http://127.0.0.1:40001
  # ============================ Spring Boot Admin ============================

management:
  endpoints:
    web:
      exposure:
        include: '*'

# ============================ MyBatis Plus =========================================
#mybatis-plus:
  #global-config:
    #逻辑删除
    #db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      #logic-delete-field: flag
      # 逻辑已删除值(默认为 1)
      #logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      #logic-not-delete-value: 0