# H2 DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/h2/schema-customer-h2.sql
    username: root
    password: root
  sql:
    init:
      schema-locations: classpath:db/h2/schema-customer-h2.sql
      data-locations: classpath:db/h2/data-customer-h2.sql

# DB DataSource Config