easy-es:
  # 默认为 true, 若为 false 则认为不启用本框架
  enable: true
  # es的连接地址,必须含端口 若为集群,则可以用逗号隔开 例如:127.0.0.1:9200,127.0.0.2:9200
  address: 127.0.0.1:9200
  # 若无 则可省略此行配置
  # username: elastic
  # 若无 则可省略此行配置
  # password: WG7WVmuNMtM4GwNYkyWH
  # 默认为http
  # schema: http

  # 心跳策略时间 单位:ms
  # keep-alive-millis: 18000
  # 连接超时时间 单位:ms
  # connectTimeout: 5000
  # 通信超时时间 单位:ms
  # socketTimeout: 5000

  # 请求超时时间 单位:ms 这个属性目前是：Cannot resolve configuration property 'easy-es.requestTimeout'
  # requestTimeout: 5000

  # 连接请求超时时间 单位:ms
  # connectionRequestTimeout: 5000

  # 最大连接数 单位:个
  # maxConnTotal: 100
  # 最大连接路由数 单位:个
  #maxConnPerRoute: 100

  # 默认为true 打印banner 若您不期望打印banner,可配置为false
  banner: false
  global-config:
    #索引处理模式,smoothly:平滑模式,默认开启此模式, not_smoothly:非平滑模式, manual:手动模式
    #process_index_mode: smoothly
    # 开启控制台打印通过本框架生成的DSL语句,默认为开启,测试稳定后的生产环境建议关闭,以提升少量性能
    print-dsl: true
    # 当前项目是否分布式项目,默认为true,在非手动托管索引模式下,若为分布式项目则会获取分布式锁,非分布式项目只需synchronized锁.
    #distributed: false
    # 异步处理索引是否阻塞主线程 默认阻塞 数据量过大时调整为非阻塞异步进行 项目启动更快
    #asyncProcessIndexBlocking: true
    # 分布式环境下,平滑模式,当前客户端激活最新索引最大重试次数若数据量过大,重建索引数据迁移时间超过60*(180/60)=180分钟时,可调大此参数值,此参数值决定最大重试次数,超出此次数后仍未成功,则终止重试并记录异常日志
    #activeReleaseIndexMaxRetry: 60
    # 分布式环境下,平滑模式,当前客户端激活最新索引最大重试次数 若数据量过大,重建索引数据迁移时间超过60*(180/60)=180分钟时,可调大此参数值 此参数值决定多久重试一次 单位:秒
    #activeReleaseIndexFixedDelay: 180

    #db-config:
      # 是否开启下划线转驼峰 默认为false
      # map-underscore-to-camel-case: false
      # 索引前缀,可用于区分环境  默认为空 用法和MP一样
      #table-prefix: it6666_
      # id生成策略 customize为自定义,id值由用户生成,比如取MySQL中的数据id,如缺省此项配置,则id默认策略为es自动生成
      # https://www.easy-es.cn/pages/9a3e4c/
      #id-type: customize
      # 字段更新策略 默认为not_null
      #field-strategy: not_empty
      # 默认开启,查询若指定了size超过1w条时也会自动开启,开启后查询所有匹配数据,若不开启,会导致无法获取数据总条数,其它功能不受影响.
      #enable-track-total-hits: true
      # 数据刷新策略,默认为不刷新
      #refresh-policy: immediate
      # 是否全局开启must查询类型转换为filter查询类型 默认为false不转换
      #enable-must2-filter: false

logging:
  level:
    # 开启trace级别日志,在开发时可以开启此配置,则控制台可以打印es全部请求信息及DSL语句,为了避免重复,
    # 开启此项配置后,可以将EE的print-dsl设置为false.
    tracer: trace

server:
  port: 50001

#自定义 swagger信息
swagger:
  base-package: top.it6666
  description: Service-Easy-Es-API API document
  title: Service-Easy-Es-API
  version: 1.0

# mvc
spring:
  mvc:
    pathmatch:
      # 路径匹配策略  spring-boot 2.6 之后更改了匹配策略
      # Springboot2.6以后将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser，导致出错
      matching-strategy: ant_path_matcher