# 自定义 knife4j 信息
swagger:
  base-package: top.it6666.controller
  description: Service-Swagger-API API document
  title: Service-Swagger-API
  version: 1.0

swagger2:
  title: Service-Swagger V2 App
  description: Service-Swagger V2 App API document

# mvc
spring:
  mvc:
    pathmatch:
      # 路径匹配策略  spring-boot 2.6 之后更改了匹配策略
      # Springboot2.6以后将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser，导致出错
      matching-strategy: ant_path_matcher

server:
  port: 50003